config/routes.rb
Rails.application.routes.draw do
  root "todo_entries#index"

  resources :todo_entries
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/todo_entry.rb
class TodoEntry < ApplicationRecord
  validates :title, presence: true
  validates :body, presence: true, length: { minimum: 10 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/todo_entries_controller.rb
class TodoEntriesController < ApplicationController
  def index
    @todo_entries = TodoEntry.all
  end

  def show
    @todo_entries = TodoEntry.find(params[:id])
  end

  def new
    @todo_entries = TodoEntry.new
  end

  def create
    @todo_entries = TodoEntry.new(todo_params)

    if @todo_entries.save
      redirect_to @todo_entries
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @todo_entries = TodoEntry.find(params[:id])
  end

  def update
    @todo_entries = TodoEntry.find(params[:id])
    if @todo_entries.update(todo_params)
      redirect_to @todo_entries
    else
      render :edit, status: :unprocessable_entity
    end
  end

  private
    def todo_params
      params.require(:todo_entry).permit(:title, :body)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/todo_entries_helper.rb
module TodoEntriesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Todo</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/todo_entries/index.html.erb
<h1>Todo</h1>

<ul>
  <% @todo_entries.each do |todo| %>
    <li>
      <%= link_to todo.title, todo %>
    </li>
  <% end %>
</ul>

<%= link_to "New Todo", new_todo_entry_path%>

app/views/todo_entries/new.html.erb
<h1> New Todo</h1>

<%= form_with model: @todo_entries do |form|%>
  <div>
    <%= form.label :title %><br>
    <%= form.text_field :title %>
    <% @todo_entries.errors.full_messages_for(:title).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>
  <div>
    <%= form.label :body %><br>
    <%= form.text_field :body %>
    <% @todo_entries.errors.full_messages_for(:body).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>
  <div>
    <%= form.submit %>
  </div>
  <a href="/todo_entries/">Back</a>
<% end%>

app/views/todo_entries/show.html.erb
<div>
  <h1><%= @todo_entries.title %></h1>
  <p> <%= @todo_entries.body %> </p>
  <a href="/todo_entries/">Back</a>
</div>